Feature/6 establish rotate functional
Alexandr1907/architect-patterns pull request #10
Opened 2022-12-18 13:17 UTC by alexdecline

Rotate command

2022-12-18 16:15 UTC, Alexandr1907 requested changes
нужно поправить по комментам, особенно то что касается класса Direction

2022-12-18 16:15 UTC, Alexandr1907 commented on src/main/java/com/otus/spaceBattle/command/Rotate.java
> +        rotatableDirectionNullCheck();
тут, наверное, имеет смысл проверять и угловую скорость на нул

2022-12-18 16:15 UTC, Alexandr1907 commented on src/main/java/com/otus/spaceBattle/dto/Direction.java
> +public interface Direction {
соответственно этот класс не нужен, т.к. функционал описан классом Coords

2022-12-18 16:15 UTC, Alexandr1907 commented on src/main/java/com/otus/spaceBattle/action/Rotatable.java
> +    Direction getDirection();
Тут должна выполняться работа с вектором скорости описанном классом Coords

2022-12-18 16:15 UTC, Alexandr1907 commented on src/main/java/com/otus/spaceBattle/action/Rotatable.java
> +    void setDirection(Direction direction);
И тут должна выполняться работа с вектором скорости описанном классом Coords. Изменение угла поворота изменяет направление вектора скорости (координаты вектора)

2022-12-18 16:15 UTC, Alexandr1907 commented on src/test/java/com/otus/spaceBattle/command/RotateTest.java
> +    void test4() {
плюс еще тест на нул угловую скорость

2022-12-18 16:15 UTC, Alexandr1907 commented on src/test/java/com/otus/spaceBattle/command/RotateTest.java
> +        when(direction.next(any(Integer.class))).thenReturn(direction);
тут будет использоваться класс Coords. Не знаю стоит ли его интерфейсом покрывать или такой служебный класс можно просто оставить как класс. Надо подумать.

2022-12-18 16:31 UTC, alexdecline commented on src/main/java/com/otus/spaceBattle/command/Rotate.java
> +        rotatableDirectionNullCheck();
Она примитив) тоже сначала хотел проверить

2022-12-19 18:08 UTC, Alexandr1907 approved these changes
все вопросы решили голосом, все ок)

2022-12-19 18:09 UTC, merged