add SpeedChangeable interface and execution logic
Alexandr1907/architect-patterns pull request #11
Opened 2022-12-21 16:53 UTC by Egor-kokhan

2022-12-21 18:22 UTC, alexdecline commented on src/main/java/com/otus/spaceBattle/command/SpeedChanger.java
> +        int speed = speedChangeable.getSpeed();
Тут можно npe словить

2022-12-21 20:00 UTC, Alexandr1907 requested changes

2022-12-21 20:00 UTC, Alexandr1907 commented on src/main/java/com/otus/spaceBattle/command/SpeedChanger.java
> +        int speed = speedChangeable.getSpeed();
поддерживаю, по аналогии с классом Rotate надо @NonNull аннтоацию на поле повесить) и у меня в классе Move можешь к такому-же виду привести? чтоб в одном стиле всё было)

2022-12-21 20:00 UTC, Alexandr1907 commented on src/test/java/com/otus/spaceBattle/TestData.java
> +  public static final int STARTED_SPEED = 10;
тут я бы строку пропустил после END_POSITION  чтоб визуально разделить разный "функционал"

2022-12-21 20:00 UTC, Alexandr1907 commented on src/test/java/com/otus/spaceBattle/command/ChangeSpeedTest.java
> +    void changeSpeed() {
нужны еще тесты на случай, если вызовы методов будут ошибку выбрасывать.
Как у меня в  MoveTest execute_shouldThrowException...

Так понял это надо, чтоб подсветить, что наш класс-команда не обрабатывает ошибку никак и вверх пробрасывает её

2022-12-23 09:57 UTC, Alexandr1907 requested changes

2022-12-23 09:57 UTC, Alexandr1907 commented on src/test/java/com/otus/spaceBattle/command/ChangeSpeedTest.java
> +    void executeShouldThrowExceptionIfGetSpeedNotAvailable() {
а сет спид?

2022-12-26 18:57 UTC, alexdecline approved these changes

2022-12-26 19:00 UTC, alexdecline approved these changes

2022-12-26 19:04 UTC, Alexandr1907 approved these changes

2023-01-07 16:36 UTC, merged