Rotation velocity change
Alexandr1907/architect-patterns pull request #12
Opened 2022-12-26 09:40 UTC by Mamol27

2022-12-26 12:22 UTC, Alexandr1907 requested changes

2022-12-26 12:22 UTC, Alexandr1907 commented on src/test/java/com/otus/spaceBattle/command/ChangeAngularVelocityTest.java
> +    }
думаю тут аналогично надо накидать тестов на то, что если метод интерфейса пробрасывает рантайм эксепшен, метод изменения угловой скорости падает с этим же эксепшеном. Хотя на мой взгляд, это довольно странный тест)

2022-12-26 18:59 UTC, alexdecline approved these changes

2023-01-11 16:51 UTC, Alexandr1907 commented
я тут при решении конфликта что-то накосарезил, в итоге просто в мастер залил через мерж и пуш в идеи. Но по идее в самом ПР все ок

2023-01-11 16:51 UTC, closed without merging